# Generated by Django 2.1.15 on 2020-06-10 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        ('interview', '0003_auto_20200610_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddInt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dated', models.DateTimeField(blank=True, null=True)),
                ('interviewed', models.BooleanField()),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.Recomendation')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Employee')),
            ],
        ),
    ]
