# Generated by Django 3.0.6 on 2020-06-11 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addint', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept', models.CharField(blank=True, default='none', max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='addint',
            name='concept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addint.Concept'),
        ),
    ]
