# Generated by Django 3.0.6 on 2020-06-11 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addint', '0002_auto_20200610_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addint',
            name='concept',
        ),
        migrations.AddField(
            model_name='addint',
            name='hire',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='addint',
            name='interviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Concept',
        ),
    ]
