# Generated by Django 2.1.15 on 2020-06-10 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='none', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(default='none', max_length=100)),
                ('identification', models.IntegerField(blank=True, null=True)),
                ('mobile', models.CharField(default='0', max_length=15)),
                ('department', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='employee.Department')),
            ],
        ),
        migrations.CreateModel(
            name='JobName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='none', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='jobname',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='employee.JobName'),
        ),
    ]
