# Generated by Django 3.0.6 on 2020-06-11 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.CharField(blank=True, default='None', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='doi',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mobile',
            field=models.IntegerField(),
        ),
    ]
