# Generated by Django 3.0.3 on 2020-06-23 01:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aca_concordance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.CharField(blank=True, default='0', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Aca_level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='0', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Apareance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.CharField(blank=True, default='0', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Aspirations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.CharField(blank=True, default='0', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Interviewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='0', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job_afinity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.CharField(blank=True, default='0', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ove_result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.CharField(blank=True, default='0', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Puntuality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.CharField(blank=True, default='0', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recomendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.CharField(blank=True, default='0', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Responsability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.CharField(blank=True, default='0', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Verbal_com',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.CharField(blank=True, default='0', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dated', models.DateTimeField(blank=True, null=True)),
                ('passport', models.BooleanField(default=False)),
                ('dis_travel', models.BooleanField(default=False)),
                ('visa', models.BooleanField(default=False)),
                ('no_children', models.IntegerField(blank=True, null=True)),
                ('w_live', models.CharField(blank=True, max_length=100, null=True)),
                ('dis_inc', models.DateTimeField(blank=True, null=True)),
                ('strenghts', models.CharField(blank=True, max_length=100, null=True)),
                ('weakness', models.CharField(blank=True, max_length=100, null=True)),
                ('int_rel', models.CharField(blank=True, max_length=100, null=True)),
                ('team_work', models.CharField(blank=True, max_length=100, null=True)),
                ('other_academy', models.CharField(blank=True, max_length=50, null=True)),
                ('observations', models.CharField(blank=True, max_length=100, null=True)),
                ('aca_concordance', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='interview.Aca_concordance')),
                ('aca_level', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='interview.Aca_level')),
                ('apareance', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='interview.Apareance')),
                ('aspirations', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='interview.Aspirations')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.Employee')),
                ('interviewer', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='interview.Interviewer')),
                ('job_afinity', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='interview.Job_afinity')),
                ('ove_result', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='interview.Ove_result')),
                ('puntuality', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='interview.Puntuality')),
                ('recomendation', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='interview.Recomendation')),
                ('responsability', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='interview.Responsability')),
                ('toUser', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('verbal_com', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='interview.Verbal_com')),
            ],
        ),
    ]
