# Generated by Django 2.1.15 on 2020-06-10 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aca_concordance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.CharField(blank=True, default='0', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Aca_level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='0', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Apareance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.CharField(blank=True, default='0', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Aspirations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.CharField(blank=True, default='0', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dated', models.DateField(blank=True, null=True)),
                ('hour', models.DateField(blank=True, null=True)),
                ('passport', models.BooleanField(default=False)),
                ('dis_travel', models.BooleanField(default=False)),
                ('visa', models.BooleanField(default=False)),
                ('no_children', models.IntegerField(blank=True, null=True)),
                ('w_live', models.CharField(blank=True, max_length=100, null=True)),
                ('dis_inc', models.DateField(blank=True, null=True)),
                ('strenghts', models.CharField(blank=True, max_length=100, null=True)),
                ('weakness', models.CharField(blank=True, max_length=100, null=True)),
                ('int_rel', models.CharField(blank=True, max_length=100, null=True)),
                ('team_work', models.CharField(blank=True, max_length=100, null=True)),
                ('other_academy', models.CharField(blank=True, max_length=50, null=True)),
                ('observations', models.CharField(blank=True, max_length=100, null=True)),
                ('aca_concordance', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='interview.Aca_concordance')),
                ('aca_level', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='interview.Aca_level')),
                ('apareance', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='interview.Apareance')),
                ('aspirations', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='interview.Aspirations')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Interviewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='0', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job_afinity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.CharField(blank=True, default='0', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ove_result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.CharField(blank=True, default='0', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Puntuality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.CharField(blank=True, default='0', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recomendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.CharField(blank=True, default='0', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Responsability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.CharField(blank=True, default='0', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Verbal_com',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.CharField(blank=True, default='0', max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='interview',
            name='interviewer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='interview.Interviewer'),
        ),
        migrations.AddField(
            model_name='interview',
            name='job_afinity',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='interview.Job_afinity'),
        ),
        migrations.AddField(
            model_name='interview',
            name='ove_result',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='interview.Ove_result'),
        ),
        migrations.AddField(
            model_name='interview',
            name='puntuality',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='interview.Puntuality'),
        ),
        migrations.AddField(
            model_name='interview',
            name='recomendation',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='interview.Recomendation'),
        ),
        migrations.AddField(
            model_name='interview',
            name='responsability',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='interview.Responsability'),
        ),
        migrations.AddField(
            model_name='interview',
            name='verbal_com',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='interview.Verbal_com'),
        ),
    ]
