# Generated by Django 2.1.15 on 2020-06-10 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_remove_interview_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='dated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interview',
            name='dis_inc',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
