# Generated by Django 2.1.15 on 2020-07-15 17:12

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enterprise', models.CharField(choices=[('IMEXHS', 'IMEXHS'), ('RIMAB', 'RIMAB'), ('UT', 'UT'), ('COLSUBSIDIO', 'COLSUBSIDIO')], default='RIMAB', max_length=2)),
                ('t_contract', models.CharField(choices=[('FIJO 1 MES', 'FIJO 1 MES'), ('FIJO 3 MESES', 'FIJO 3 MESES'), ('FIJO 4 MESES', 'FIJO 4 MESES'), ('FIJO 6 MESES', 'FIJO 6 MESES'), ('FIJO 7 MESES', 'FIJO 7 MESES')], default='FIJO 3 MESES', max_length=2)),
                ('idate_ctr', models.DateField()),
                ('edate_ctr', models.DateField()),
                ('not_date', models.DateField()),
                ('notified', models.BooleanField()),
                ('renew_ctr', models.BooleanField()),
                ('observation', models.CharField(max_length=300, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2020, 7, 15, 17, 12, 10, 516745, tzinfo=utc))),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Employee')),
            ],
        ),
    ]
