# Generated by Django 2.1.15 on 2020-07-15 17:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hhrr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracts',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 15, 17, 15, 17, 328500, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='enterprise',
            field=models.CharField(choices=[('IMEXHS', 'IMEXHS'), ('RIMAB', 'RIMAB'), ('UT', 'UT'), ('COLSUBSIDIO', 'COLSUBSIDIO')], default='RIMAB', max_length=30),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='t_contract',
            field=models.CharField(choices=[('FIJO 1 MES', 'FIJO 1 MES'), ('FIJO 3 MESES', 'FIJO 3 MESES'), ('FIJO 4 MESES', 'FIJO 4 MESES'), ('FIJO 6 MESES', 'FIJO 6 MESES'), ('FIJO 7 MESES', 'FIJO 7 MESES')], default='FIJO 3 MESES', max_length=30),
        ),
    ]
